import Link from "next/link";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Terms of Service — Quantalyze",
};

const LAST_UPDATED = "28 February 2026";
const CONTACT_EMAIL = "hello@quantalyze.me";

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-[#0a0a0f] text-white">
      {/* Nav */}
      <header className="mx-auto flex max-w-4xl items-center justify-between px-6 py-5">
        <Link href="/" className="text-lg font-semibold tracking-tight text-white">
          Quantalyze
        </Link>
        <Link
          href="/login"
          className="rounded-full border border-white/20 bg-white/5 px-5 py-2 text-sm font-medium text-white/90 transition hover:bg-white/10"
        >
          Sign in
        </Link>
      </header>

      <main className="mx-auto max-w-3xl px-6 pb-24 pt-12">
        <h1 className="mb-2 text-3xl font-bold text-white">Terms of Service</h1>
        <p className="mb-12 text-sm text-white/40">Last updated: {LAST_UPDATED}</p>

        <div className="space-y-10 text-[15px] leading-relaxed text-white/70">

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">1. Acceptance of terms</h2>
            <p>
              By accessing or using Quantalyze (&ldquo;the Service&rdquo;), you agree to be
              bound by these Terms of Service. If you do not agree, do not use the Service.
              These terms apply to all users including individuals and organisations accessing
              the Service on behalf of a team.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">2. Description of service</h2>
            <p>
              Quantalyze provides AI-powered analysis of publicly available earnings call
              transcripts for companies listed on Indian stock exchanges. The Service uses
              large language models to identify language shifts, classify signals, and score
              executive communication patterns across quarterly results.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">3. Not financial advice</h2>
            <div className="rounded-lg border border-amber-500/30 bg-amber-500/10 px-5 py-4 text-amber-200/80">
              <p className="font-semibold text-amber-300 mb-1">Important disclaimer</p>
              <p>
                All content generated by Quantalyze — including signal classifications,
                evasiveness scores, summaries, and takeaways — is produced by artificial
                intelligence and is provided for <strong>informational purposes only</strong>.
                It does not constitute financial advice, investment advice, trading advice,
                or any other kind of advice. You should not make any investment or financial
                decision based solely on the outputs of this Service. Always conduct your
                own independent research and consult a qualified financial advisor where
                appropriate.
              </p>
            </div>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">4. Accounts and access</h2>
            <ul className="list-disc space-y-2 pl-5">
              <li>You must provide accurate information when creating an account.</li>
              <li>You are responsible for maintaining the security of your account credentials.</li>
              <li>You may not share your account with others or use the Service to provide
                access to third parties who have not agreed to these terms.</li>
              <li>We reserve the right to suspend or terminate accounts that violate these terms.</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">5. Acceptable use</h2>
            <p className="mb-3">You agree not to:</p>
            <ul className="list-disc space-y-2 pl-5">
              <li>Use the Service for any unlawful purpose or in violation of applicable regulations</li>
              <li>Attempt to reverse-engineer, scrape, or extract data from the Service at scale</li>
              <li>Resell, redistribute, or sublicense access to the Service without our written permission</li>
              <li>Use the Service to generate content intended to mislead investors or manipulate markets</li>
              <li>Interfere with or disrupt the integrity or performance of the Service</li>
            </ul>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">6. Third-party integrations</h2>
            <p>
              The Service integrates with Google (Gmail, OAuth) and Slack. By connecting these
              integrations, you also agree to the respective terms of service of those platforms.
              We are not responsible for the availability or conduct of these third-party services.
              You may disconnect any integration at any time from Settings → Connections.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">7. Intellectual property</h2>
            <p>
              The Quantalyze platform, including its software, design, and AI model prompts,
              is our intellectual property. Earnings call transcripts analysed by the Service
              are publicly available documents owned by the respective companies and exchanges.
              You retain ownership of any data you bring to the Service (e.g., your account
              information). AI-generated analysis outputs are provided to you for your personal
              or organisational use and may not be redistributed commercially without permission.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">8. Accuracy and availability</h2>
            <p>
              AI-generated analysis may contain errors, omissions, or hallucinations. We do
              not guarantee the accuracy, completeness, or timeliness of any analysis output.
              The Service is provided on a best-effort basis and we do not guarantee uninterrupted
              availability. We reserve the right to modify, suspend, or discontinue any part of
              the Service at any time with reasonable notice.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">9. Limitation of liability</h2>
            <p>
              To the maximum extent permitted by applicable law, Quantalyze shall not be liable
              for any indirect, incidental, special, consequential, or punitive damages,
              including loss of profits or investment losses, arising from your use of or
              inability to use the Service. Our total liability shall not exceed the amount
              paid by you for the Service in the three months preceding the claim.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">10. Modifications to terms</h2>
            <p>
              We may update these Terms of Service at any time. We will notify you of material
              changes by email or by posting a notice on the platform. Continued use of the
              Service after updated terms are posted constitutes acceptance of the new terms.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">11. Governing law</h2>
            <p>
              These terms are governed by the laws of India. Any disputes arising under
              these terms shall be subject to the exclusive jurisdiction of the courts
              in Mumbai, Maharashtra.
            </p>
          </section>

          <section>
            <h2 className="mb-3 text-base font-semibold text-white">12. Contact</h2>
            <p>
              For any questions about these Terms of Service, contact us at{" "}
              <a href={`mailto:${CONTACT_EMAIL}`} className="text-sky-400 hover:underline">
                {CONTACT_EMAIL}
              </a>.
            </p>
          </section>
        </div>
      </main>

      <footer className="border-t border-white/5">
        <div className="mx-auto flex max-w-4xl flex-col items-center justify-between gap-4 px-6 py-8 text-xs text-white/30 sm:flex-row">
          <span>© {new Date().getFullYear()} Quantalyze. All rights reserved.</span>
          <div className="flex gap-6">
            <Link href="/privacy" className="hover:text-white/60 transition">Privacy Policy</Link>
            <Link href="/terms" className="text-white/50">Terms of Service</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
