/**
 * Top 500 listed companies by market cap (SEBI categorization Dec 2025).
 * Source: wealth/AverageMarketCapitalization31Dec2025.pdf
 * Sectors from NIFTY200 registry + keyword inference.
 */

export interface ListedCompany {
  rank: number;
  name: string;
  nse: string;
  category: "Large Cap" | "Mid Cap" | "Small Cap";
  sector: string;
}

export const LISTED_COMPANIES: ListedCompany[] = [
  { rank: 1, name: "Reliance Industries Ltd", nse: "RELIANCE", category: "Large Cap", sector: "Conglomerate" },
  { rank: 2, name: "HDFC Bank Ltd.", nse: "HDFCBANK", category: "Large Cap", sector: "Banking" },
  { rank: 3, name: "Bharti Airtel Ltd.", nse: "BHARTIARTL", category: "Large Cap", sector: "Telecom" },
  { rank: 4, name: "Tata Consultancy Services Ltd.", nse: "TCS", category: "Large Cap", sector: "IT" },
  { rank: 5, name: "ICICI Bank Ltd.", nse: "ICICIBANK", category: "Large Cap", sector: "Banking" },
  { rank: 6, name: "State Bank Of India", nse: "SBIN", category: "Large Cap", sector: "Banking" },
  { rank: 7, name: "Infosys Ltd", nse: "INFY", category: "Large Cap", sector: "IT" },
  { rank: 8, name: "Bajaj Finance Limited", nse: "BAJFINANCE", category: "Large Cap", sector: "NBFC" },
  { rank: 9, name: "Life Insurance Corporation of India", nse: "LICI", category: "Large Cap", sector: "Insurance" },
  { rank: 10, name: "Hindustan Unilever Ltd.", nse: "HINDUNILVR", category: "Large Cap", sector: "FMCG" },
  { rank: 11, name: "Larsen & Toubro Limited", nse: "LT", category: "Large Cap", sector: "Infra" },
  { rank: 12, name: "ITC Ltd", nse: "ITC", category: "Large Cap", sector: "FMCG" },
  { rank: 13, name: "Maruti Suzuki India Ltd.", nse: "MARUTI", category: "Large Cap", sector: "Auto" },
  { rank: 14, name: "Mahindra & Mahindra Ltd.", nse: "M&M", category: "Large Cap", sector: "Auto" },
  { rank: 15, name: "HCL Technologies Ltd", nse: "HCLTECH", category: "Large Cap", sector: "IT" },
  { rank: 16, name: "Kotak Mahindra Bank Ltd.", nse: "KOTAKBANK", category: "Large Cap", sector: "Banking" },
  { rank: 17, name: "Sun Pharmaceutical Industries Ltd.", nse: "SUNPHARMA", category: "Large Cap", sector: "Pharma" },
  { rank: 18, name: "AXIS Bank Ltd.", nse: "AXISBANK", category: "Large Cap", sector: "Banking" },
  { rank: 19, name: "UltraTech Cement Ltd", nse: "ULTRACEMCO", category: "Large Cap", sector: "Cement" },
  { rank: 20, name: "Bajaj Finserv Limited", nse: "BAJAJFINSV", category: "Large Cap", sector: "NBFC" },
  { rank: 21, name: "Titan Company Limited", nse: "TITAN", category: "Large Cap", sector: "Consumer" },
  { rank: 22, name: "NTPC Limited", nse: "NTPC", category: "Large Cap", sector: "Power" },
  { rank: 23, name: "Hindustan Aeronautics Limited", nse: "HAL", category: "Large Cap", sector: "Capital Goods" },
  { rank: 24, name: "Adani Ports and Special Economic Zone Ltd", nse: "ADANIPORTS", category: "Large Cap", sector: "Infra" },
  { rank: 25, name: "Oil And Natural Gas Corporation Ltd", nse: "ONGC", category: "Large Cap", sector: "Oil & Gas" },
  { rank: 26, name: "Eternal Limited", nse: "ETERNAL", category: "Large Cap", sector: "Consumer" },
  { rank: 27, name: "Bharat Electronics Ltd.", nse: "BEL", category: "Large Cap", sector: "Capital Goods" },
  { rank: 28, name: "Adani Enterprises Ltd.", nse: "ADANIENT", category: "Large Cap", sector: "Conglomerate" },
  { rank: 29, name: "Avenue Supermarts Limited", nse: "DMART", category: "Large Cap", sector: "Consumer" },
  { rank: 30, name: "JSW Steel Limited", nse: "JSWSTEEL", category: "Large Cap", sector: "Metals" },
  { rank: 31, name: "Adani Power Limited", nse: "ADANIPOWER", category: "Large Cap", sector: "Power" },
  { rank: 32, name: "Wipro Ltd.", nse: "WIPRO", category: "Large Cap", sector: "IT" },
  { rank: 33, name: "POWER GRID CORPORATION OF INDIA LIMITED", nse: "POWERGRID", category: "Large Cap", sector: "Power" },
  { rank: 34, name: "Asian Paints Ltd.", nse: "ASIANPAINT", category: "Large Cap", sector: "Consumer" },
  { rank: 35, name: "Bajaj Auto Limited", nse: "BAJAJ-AUTO", category: "Large Cap", sector: "Auto" },
  { rank: 36, name: "Coal India Limited", nse: "COALINDIA", category: "Large Cap", sector: "Mining" },
  { rank: 37, name: "Nestle India Ltd.", nse: "NESTLEIND", category: "Large Cap", sector: "FMCG" },
  { rank: 38, name: "InterGlobe Aviation Limited", nse: "INDIGO", category: "Large Cap", sector: "Infra" },
  { rank: 39, name: "Indian Oil Corporation Ltd.", nse: "IOC", category: "Large Cap", sector: "Oil & Gas" },
  { rank: 40, name: "TATA STEEL LIMITED", nse: "TATASTEEL", category: "Large Cap", sector: "Metals" },
  { rank: 41, name: "Hindustan Zinc Ltd.", nse: "HINDZINC", category: "Large Cap", sector: "Metals" },
  { rank: 42, name: "Jio Financial Services Limited", nse: "JIOFIN", category: "Large Cap", sector: "Financial Services" },
  { rank: 43, name: "HYUNDAI MOTOR INDIA LIMITED", nse: "HYUNDAI", category: "Large Cap", sector: "Auto" },
  { rank: 44, name: "Grasim Industries Ltd", nse: "GRASIM", category: "Large Cap", sector: "Cement" },
  { rank: 45, name: "SBI Life Insurance Company Limited", nse: "SBILIFE", category: "Large Cap", sector: "Insurance" },
  { rank: 46, name: "Vedanta Limited", nse: "VEDL", category: "Large Cap", sector: "Metals" },
  { rank: 47, name: "DLF LIMITED", nse: "DLF", category: "Large Cap", sector: "Realty" },
  { rank: 48, name: "Eicher Motors Ltd.", nse: "EICHERMOT", category: "Large Cap", sector: "Auto" },
  { rank: 49, name: "Trent Ltd [Lakme Ltd]", nse: "TRENT", category: "Large Cap", sector: "Consumer" },
  { rank: 50, name: "Hindalco Industries Ltd.", nse: "HINDALCO", category: "Large Cap", sector: "Metals" },
  { rank: 51, name: "Divi\'s Laboratories Ltd.", nse: "DIVISLAB", category: "Large Cap", sector: "Pharma" },
  { rank: 52, name: "HDFC LIFE INSURANCE COMPANY LIMITED", nse: "HDFCLIFE", category: "Large Cap", sector: "Insurance" },
  { rank: 53, name: "LTIMindtree Limited", nse: "LTIM", category: "Large Cap", sector: "IT" },
  { rank: 54, name: "Indian Railway Finance Corporation", nse: "IRFC", category: "Large Cap", sector: "Financial Services" },
  { rank: 55, name: "Adani Green Energy Limited", nse: "ADANIGREEN", category: "Large Cap", sector: "Power" },
  { rank: 56, name: "Varun Beverages Limited", nse: "VBL", category: "Large Cap", sector: "FMCG" },
  { rank: 57, name: "TVS Motor Company Ltd.", nse: "TVSMOTOR", category: "Large Cap", sector: "Auto" },
  { rank: 58, name: "Pidilite Industries Ltd.", nse: "PIDILITIND", category: "Large Cap", sector: "Chemicals" },
  { rank: 59, name: "Bharat Petroleum Corpn. Ltd.", nse: "BPCL", category: "Large Cap", sector: "Oil & Gas" },
  { rank: 60, name: "Tech Mahindra Limited", nse: "TECHM", category: "Large Cap", sector: "IT" },
  { rank: 61, name: "Bajaj Holdings & Investment Limited", nse: "BAJAJHLDNG", category: "Large Cap", sector: "Financial Services" },
  { rank: 62, name: "Britannia Industries Ltd.", nse: "BRITANNIA", category: "Large Cap", sector: "FMCG" },
  { rank: 63, name: "Ambuja Cements Ltd.", nse: "AMBUJACEM", category: "Large Cap", sector: "Cement" },
  { rank: 64, name: "Tata Capital Limited", nse: "TATACAP", category: "Large Cap", sector: "Financial Services" },
  { rank: 65, name: "TATA MOTORS PASSENGER VEHICLES LIMITED", nse: "TMPV", category: "Large Cap", sector: "Auto" },
  { rank: 66, name: "Bank Of Baroda", nse: "BANKBARODA", category: "Large Cap", sector: "Banking" },
  { rank: 67, name: "Cholamandalam Investment and Finance Company Ltd", nse: "CHOLAFIN", category: "Large Cap", sector: "NBFC" },
  { rank: 68, name: "Shriram Finance Limited", nse: "SHRIRAMFIN", category: "Large Cap", sector: "NBFC" },
  { rank: 69, name: "Tata Motors Limited", nse: "TMCV", category: "Large Cap", sector: "Auto" },
  { rank: 70, name: "Punjab National Bank", nse: "PNB", category: "Large Cap", sector: "Banking" },
  { rank: 71, name: "ICICI Prudential Asset Management Company Limited", nse: "ICICIAMC", category: "Large Cap", sector: "Financial Services" },
  { rank: 72, name: "Power Finance Corporation Ltd", nse: "PFC", category: "Large Cap", sector: "Financial Services" },
  { rank: 73, name: "Solar Industries India Limited", nse: "SOLARINDS", category: "Large Cap", sector: "Chemicals" },
  { rank: 74, name: "MUTHOOT FINANCE LIMITED", nse: "MUTHOOTFIN", category: "Large Cap", sector: "NBFC" },
  { rank: 75, name: "Tata Power Co. Ltd", nse: "TATAPOWER", category: "Large Cap", sector: "Power" },
  { rank: 76, name: "Cipla Ltd.", nse: "CIPLA", category: "Large Cap", sector: "Pharma" },
  { rank: 77, name: "Torrent Pharmaceuticals Ltd.", nse: "TORNTPHARM", category: "Large Cap", sector: "Pharma" },
  { rank: 78, name: "Godrej Consumer Products Ltd.", nse: "GODREJCP", category: "Large Cap", sector: "FMCG" },
  { rank: 79, name: "Lodha Developers Limited", nse: "LODHA", category: "Large Cap", sector: "Realty" },
  { rank: 80, name: "HDFC Asset Management Company Limited", nse: "HDFCAMC", category: "Large Cap", sector: "Financial Services" },
  { rank: 81, name: "Gail (India) Ltd.", nse: "GAIL", category: "Large Cap", sector: "Oil & Gas" },
  { rank: 82, name: "Canara Bank", nse: "CANBK", category: "Large Cap", sector: "Banking" },
  { rank: 83, name: "Max Healthcare Institute Limited", nse: "MAXHEALTH", category: "Large Cap", sector: "Healthcare" },
  { rank: 84, name: "Siemens Energy India Limited", nse: "ENRIN", category: "Large Cap", sector: "Capital Goods" },
  { rank: 85, name: "Siemens Ltd.", nse: "SIEMENS", category: "Large Cap", sector: "Capital Goods" },
  { rank: 86, name: "Mazagon Dock Shipbuilders Limited", nse: "MAZDOCK", category: "Large Cap", sector: "Capital Goods" },
  { rank: 87, name: "Bosch Ltd", nse: "BOSCHLTD", category: "Large Cap", sector: "Auto" },
  { rank: 88, name: "ABB India Limited", nse: "ABB", category: "Large Cap", sector: "Capital Goods" },
  { rank: 89, name: "Samvardhana Motherson International Limited", nse: "MOTHERSON", category: "Large Cap", sector: "Auto" },
  { rank: 90, name: "Cummins India Ltd.", nse: "CUMMINSIND", category: "Large Cap", sector: "Capital Goods" },
  { rank: 91, name: "TATA CONSUMER PRODUCTS LIMITED", nse: "TATACONSUM", category: "Large Cap", sector: "FMCG" },
  { rank: 92, name: "CG Power and Industrial Solutions Limited", nse: "CGPOWER", category: "Large Cap", sector: "Capital Goods" },
  { rank: 93, name: "LG Electronics India Limited", nse: "LGEINDIA", category: "Large Cap", sector: "" },
  { rank: 94, name: "Polycab India Limited", nse: "POLYCAB", category: "Large Cap", sector: "Capital Goods" },
  { rank: 95, name: "Union Bank of India", nse: "UNIONBANK", category: "Large Cap", sector: "Banking" },
  { rank: 96, name: "Adani Energy Solutions Limited", nse: "ADANIENSOL", category: "Large Cap", sector: "Power" },
  { rank: 97, name: "Apollo Hospitals Enterprises Ltd.", nse: "APOLLOHOSP", category: "Large Cap", sector: "Healthcare" },
  { rank: 98, name: "Indian Hotels Co. Ltd", nse: "INDHOTEL", category: "Large Cap", sector: "Consumer" },
  { rank: 99, name: "Hero MotoCorp Limited", nse: "HEROMOTOCO", category: "Large Cap", sector: "Auto" },
  { rank: 100, name: "Dr. Reddy\'s Laboratories Ltd.", nse: "DRREDDY", category: "Large Cap", sector: "Pharma" },
  { rank: 101, name: "Shree Cements Ltd.", nse: "SHREECEM", category: "Mid Cap", sector: "Cement" },
  { rank: 102, name: "JINDAL STEEL LIMITED", nse: "JINDALSTEL", category: "Mid Cap", sector: "Metals" },
  { rank: 103, name: "IDBI Bank Ltd", nse: "IDBI", category: "Mid Cap", sector: "Banking" },
  { rank: 105, name: "BSE Ltd.", nse: "--", category: "Mid Cap", sector: "" },
  { rank: 106, name: "Mankind Pharma Limited", nse: "MANKIND", category: "Mid Cap", sector: "Pharma" },
  { rank: 107, name: "Indian Bank", nse: "INDIANB", category: "Mid Cap", sector: "Banking" },
  { rank: 108, name: "INDUS TOWERS LIMITED", nse: "INDUSTOWER", category: "Mid Cap", sector: "Telecom" },
  { rank: 109, name: "United Spirits Limited", nse: "UNITDSPR", category: "Mid Cap", sector: "FMCG" },
  { rank: 110, name: "GMR Airports Limited", nse: "GMRAIRPORT", category: "Mid Cap", sector: "Infra" },
  { rank: 111, name: "REC LIMITED", nse: "RECLTD", category: "Mid Cap", sector: "Financial Services" },
  { rank: 112, name: "Zydus Lifesciences Limited", nse: "ZYDUSLIFE", category: "Mid Cap", sector: "Pharma" },
  { rank: 113, name: "ICICI Lombard General Insurance Company Limited", nse: "ICICIGI", category: "Mid Cap", sector: "Insurance" },
  { rank: 114, name: "Billionbrains Garage Ventures Limited", nse: "GROWW", category: "Mid Cap", sector: "" },
  { rank: 115, name: "Dixon Technologies (India) Limited", nse: "DIXON", category: "Mid Cap", sector: "Consumer" },
  { rank: 116, name: "VODAFONE IDEA LIMITED", nse: "IDEA", category: "Mid Cap", sector: "Telecom" },
  { rank: 117, name: "Havells India Limited", nse: "HAVELLS", category: "Mid Cap", sector: "Consumer" },
  { rank: 118, name: "Marico Limited", nse: "MARICO", category: "Mid Cap", sector: "FMCG" },
  { rank: 119, name: "Hindustan Petroleum Corporation Ltd", nse: "HINDPETRO", category: "Mid Cap", sector: "Oil & Gas" },
  { rank: 120, name: "Waaree Energies Limited", nse: "WAAREEENER", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 121, name: "Bajaj Housing Finance Limited", nse: "BAJAJHFL", category: "Mid Cap", sector: "Financial Services" },
  { rank: 122, name: "Dabur India Ltd.", nse: "DABUR", category: "Mid Cap", sector: "FMCG" },
  { rank: 123, name: "Lupin Ltd", nse: "LUPIN", category: "Mid Cap", sector: "Pharma" },
  { rank: 124, name: "JSW Energy Limited", nse: "JSWENERGY", category: "Mid Cap", sector: "Power" },
  { rank: 125, name: "ICICI Prudential Life Insurance Company Limited", nse: "ICICIPRULI", category: "Mid Cap", sector: "Insurance" },
  { rank: 126, name: "Persistent Systems Limited", nse: "PERSISTENT", category: "Mid Cap", sector: "IT" },
  { rank: 127, name: "Bharti Hexacom Limited", nse: "BHARTIHEXA", category: "Mid Cap", sector: "Telecom" },
  { rank: 128, name: "Info Edge(India) Ltd.", nse: "NAUKRI", category: "Mid Cap", sector: "Financial Services" },
  { rank: 129, name: "SRF Ltd.", nse: "SRF", category: "Mid Cap", sector: "Chemicals" },
  { rank: 130, name: "Bharat Heavy Electricals Ltd.", nse: "BHEL", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 131, name: "HITACHI ENERGY INDIA LIMITED", nse: "POWERINDIA", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 132, name: "Meesho Limited", nse: "MEESHO", category: "Mid Cap", sector: "" },
  { rank: 133, name: "NTPC GREEN ENERGY LIMITED", nse: "NTPCGREEN", category: "Mid Cap", sector: "Power" },
  { rank: 134, name: "NHPC Limited", nse: "NHPC", category: "Mid Cap", sector: "Power" },
  { rank: 135, name: "PB Fintech Limited", nse: "POLICYBZR", category: "Mid Cap", sector: "Financial Services" },
  { rank: 136, name: "SBI CARDS AND PAYMENT SERVICES LIMITED", nse: "SBICARD", category: "Mid Cap", sector: "Financial Services" },
  { rank: 137, name: "Ashok Leyland Ltd.", nse: "ASHOKLEY", category: "Mid Cap", sector: "Auto" },
  { rank: 138, name: "SUZLON ENERGY LTD.", nse: "SUZLON", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 139, name: "Aditya Birla Capital Ltd", nse: "ABCAPITAL", category: "Mid Cap", sector: "Financial Services" },
  { rank: 140, name: "One 97 Communications Limited", nse: "PAYTM", category: "Mid Cap", sector: "Financial Services" },
  { rank: 141, name: "Indian Overseas Bank", nse: "IOB", category: "Mid Cap", sector: "Banking" },
  { rank: 142, name: "Oracle Financial Services Software Limited", nse: "OFSS", category: "Mid Cap", sector: "IT" },
  { rank: 143, name: "Lenskart Solutions Limited", nse: "LENSKART", category: "Mid Cap", sector: "" },
  { rank: 144, name: "GE Vernova T&D India Limited", nse: "GVT&D", category: "Mid Cap", sector: "" },
  { rank: 145, name: "Rail Vikas Nigam Limited", nse: "RVNL", category: "Mid Cap", sector: "Infra" },
  { rank: 146, name: "Prestige Estates Projects Limited", nse: "PRESTIGE", category: "Mid Cap", sector: "Realty" },
  { rank: 147, name: "Lloyds Metals and Energy Limited", nse: "LLOYDSME", category: "Mid Cap", sector: "Power" },
  { rank: 148, name: "UNO Minda Limited", nse: "UNOMINDA", category: "Mid Cap", sector: "" },
  { rank: 149, name: "Fortis Healthcare Ltd", nse: "FORTIS", category: "Mid Cap", sector: "Healthcare" },
  { rank: 150, name: "FSN E-Commerce Ventures Limited", nse: "NYKAA", category: "Mid Cap", sector: "Consumer" },
  { rank: 151, name: "Oil India Limited", nse: "OIL", category: "Mid Cap", sector: "Oil & Gas" },
  { rank: 152, name: "ADANI TOTAL GAS LIMITED", nse: "ATGL", category: "Mid Cap", sector: "Oil & Gas" },
  { rank: 153, name: "Coromandel International Limited", nse: "COROMANDEL", category: "Mid Cap", sector: "Chemicals" },
  { rank: 154, name: "General Insurance Corporation of India", nse: "GICRE", category: "Mid Cap", sector: "Insurance" },
  { rank: 155, name: "Yes Bank Ltd.", nse: "YESBANK", category: "Mid Cap", sector: "Banking" },
  { rank: 156, name: "Vishal Mega Mart Limited", nse: "VMM", category: "Mid Cap", sector: "Consumer" },
  { rank: 157, name: "Abbott India Ltd.", nse: "----", category: "Mid Cap", sector: "" },
  { rank: 158, name: "TORRENT POWER LIMITED", nse: "TORNTPOWER", category: "Mid Cap", sector: "Power" },
  { rank: 159, name: "Aurobindo Pharma Ltd.", nse: "AUROPHARMA", category: "Mid Cap", sector: "Pharma" },
  { rank: 160, name: "NMDC Ltd", nse: "NMDC", category: "Mid Cap", sector: "Metals" },
  { rank: 161, name: "Alkem Laboratories Limited", nse: "ALKEM", category: "Mid Cap", sector: "Pharma" },
  { rank: 162, name: "Berger Paints India Ltd", nse: "BERGEPAINT", category: "Mid Cap", sector: "Chemicals" },
  { rank: 163, name: "M.R.F. Ltd.", nse: "MRF", category: "Mid Cap", sector: "Auto" },
  { rank: 164, name: "Patanjali Foods Limited", nse: "PATANJALI", category: "Mid Cap", sector: "FMCG" },
  { rank: 165, name: "Godrej Properties Limited", nse: "GODREJPROP", category: "Mid Cap", sector: "Realty" },
  { rank: 166, name: "HDB FINANCIAL SERVICES LIMITED", nse: "HDBFS", category: "Mid Cap", sector: "Financial Services" },
  { rank: 167, name: "L&T Finance Limited", nse: "LTF", category: "Mid Cap", sector: "Financial Services" },
  { rank: 168, name: "JSW Infrastructure Limited", nse: "JSWINFRA", category: "Mid Cap", sector: "Infra" },
  { rank: 169, name: "Schaeffler India Limited", nse: "SCHAEFFLER", category: "Mid Cap", sector: "" },
  { rank: 170, name: "IndusInd Bank Ltd.", nse: "INDUSINDBK", category: "Mid Cap", sector: "Banking" },
  { rank: 171, name: "Jindal Stainless Limited", nse: "JSL", category: "Mid Cap", sector: "" },
  { rank: 172, name: "AU Small Finance Bank Limited", nse: "AUBANK", category: "Mid Cap", sector: "Financial Services" },
  { rank: 173, name: "Colgate-Palmolive (India) Ltd.", nse: "COLPAL", category: "Mid Cap", sector: "FMCG" },
  { rank: 174, name: "OBEROI REALTY LIMITED", nse: "OBEROIRLTY", category: "Mid Cap", sector: "Realty" },
  { rank: 175, name: "Bharat Forge Ltd", nse: "BHARATFORG", category: "Mid Cap", sector: "Auto" },
  { rank: 176, name: "Fertilizers and Chemicals Travancore Limited", nse: "FACT", category: "Mid Cap", sector: "Chemicals" },
  { rank: 177, name: "COFORGE LIMITED", nse: "COFORGE", category: "Mid Cap", sector: "IT" },
  { rank: 178, name: "UPL Limited", nse: "UPL", category: "Mid Cap", sector: "Chemicals" },
  { rank: 179, name: "The Phoenix Mills Ltd.", nse: "PHOENIXLTD", category: "Mid Cap", sector: "Realty" },
  { rank: 180, name: "Bank of India", nse: "BANKINDIA", category: "Mid Cap", sector: "Banking" },
  { rank: 181, name: "Tube Investments of India Ltd", nse: "TIINDIA", category: "Mid Cap", sector: "Auto" },
  { rank: 182, name: "Indian Railway Catering & Tourism Corporation Ltd", nse: "IRCTC", category: "Mid Cap", sector: "Consumer" },
  { rank: 183, name: "Bharat Dynamics Limited", nse: "BDL", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 184, name: "IDFC FIRST BANK LIMITED", nse: "IDFCFIRSTB", category: "Mid Cap", sector: "Banking" },
  { rank: 185, name: "PI Industries Limited", nse: "PIIND", category: "Mid Cap", sector: "Chemicals" },
  { rank: 186, name: "Motilal Oswal Financial Services Limited", nse: "MOTILALOFS", category: "Mid Cap", sector: "Financial Services" },
  { rank: 187, name: "Glenmark Pharmaceuticals ltd", nse: "GLENMARK", category: "Mid Cap", sector: "Pharma" },
  { rank: 188, name: "Max Financial Services Limited", nse: "MFSL", category: "Mid Cap", sector: "Insurance" },
  { rank: 189, name: "Steel Authority of India Ltd.", nse: "SAIL", category: "Mid Cap", sector: "Metals" },
  { rank: 190, name: "Federal Bank Ltd.", nse: "FEDERALBNK", category: "Mid Cap", sector: "Banking" },
  { rank: 191, name: "NIPPON LIFE INDIA ASSET MANAGEMENT LIMITED", nse: "NAM-INDIA", category: "Mid Cap", sector: "Financial Services" },
  { rank: 192, name: "Mphasis Limited", nse: "MPHASIS", category: "Mid Cap", sector: "IT" },
  { rank: 193, name: "Kalyan Jewellers India Limited", nse: "KALYANKJIL", category: "Mid Cap", sector: "Consumer" },
  { rank: 194, name: "Linde India Limited", nse: "LINDEINDIA", category: "Mid Cap", sector: "" },
  { rank: 195, name: "SUNDARAM FINANCE LTD", nse: "SUNDARMFIN", category: "Mid Cap", sector: "Financial Services" },
  { rank: 196, name: "Supreme Industries Ltd.", nse: "SUPREMEIND", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 197, name: "Biocon Ltd.", nse: "BIOCON", category: "Mid Cap", sector: "Pharma" },
  { rank: 198, name: "Tata Communications Limited", nse: "TATACOMM", category: "Mid Cap", sector: "Telecom" },
  { rank: 199, name: "Laurus Labs Limited", nse: "LAURUSLABS", category: "Mid Cap", sector: "Pharma" },
  { rank: 200, name: "Authum Investment & Infrastructure Limited", nse: "AIIL", category: "Mid Cap", sector: "Infra" },
  { rank: 201, name: "Godfrey Phillips India Ltd.", nse: "GODFRYPHLP", category: "Mid Cap", sector: "FMCG" },
  { rank: 202, name: "J.K. CEMENT LTD", nse: "JKCEMENT", category: "Mid Cap", sector: "Cement" },
  { rank: 203, name: "United Breweries Ltd.", nse: "UBL", category: "Mid Cap", sector: "" },
  { rank: 204, name: "APL Apollo Tubes Limited", nse: "APLAPOLLO", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 205, name: "Page Industries Ltd.", nse: "PAGEIND", category: "Mid Cap", sector: "Consumer" },
  { rank: 206, name: "GlaxoSmithkline Pharmaceuticals Ltd.", nse: "GLAXO", category: "Mid Cap", sector: "Pharma" },
  { rank: 207, name: "Balkrishna Industries Ltd.", nse: "BALKRISIND", category: "Mid Cap", sector: "" },
  { rank: 208, name: "ITC Hotels Limited", nse: "ITCHOTELS", category: "Mid Cap", sector: "Consumer" },
  { rank: 209, name: "Cochin Shipyard Limited", nse: "COCHINSHIP", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 210, name: "Premier Energies Limited", nse: "PREMIERENE", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 212, name: "L&T Technology Services Limited", nse: "LTTS", category: "Mid Cap", sector: "IT" },
  { rank: 213, name: "Voltas Ltd.", nse: "VOLTAS", category: "Mid Cap", sector: "Consumer" },
  { rank: 214, name: "Multi Commodity Exchange of India Ltd", nse: "----", category: "Mid Cap", sector: "" },
  { rank: 215, name: "Housing &Urban Development Corporation Ltd.", nse: "HUDCO", category: "Mid Cap", sector: "Financial Services" },
  { rank: 216360, name: "ONE WAM LIMITED", nse: "360ONE", category: "Mid Cap", sector: "" },
  { rank: 217, name: "Bank of maharashtra", nse: "MAHABANK", category: "Mid Cap", sector: "Banking" },
  { rank: 218, name: "Procter & Gamble Hygiene & Health Care Ltd.", nse: "PGHH", category: "Mid Cap", sector: "Pharma" },
  { rank: 219, name: "PETRONET LNG LTD.", nse: "PETRONET", category: "Mid Cap", sector: "Oil & Gas" },
  { rank: 220, name: "Indian Renewable Energy Development Agency Limited", nse: "IREDA", category: "Mid Cap", sector: "Financial Services" },
  { rank: 221, name: "Anthem Biosciences Limited", nse: "ANTHEM", category: "Mid Cap", sector: "" },
  { rank: 222, name: "Container Corporation Of India Ltd.", nse: "CONCOR", category: "Mid Cap", sector: "Infra" },
  { rank: 223, name: "Mahindra & Mahindra Financial Services Limited", nse: "M&MFIN", category: "Mid Cap", sector: "NBFC" },
  { rank: 224, name: "National Aluminium Co. Ltd.", nse: "NATIONALUM", category: "Mid Cap", sector: "Metals" },
  { rank: 225, name: "DALMIA BHARAT LIMITED", nse: "DALBHARAT", category: "Mid Cap", sector: "Cement" },
  { rank: 226, name: "Jubilant Foodworks Limited", nse: "JUBLFOOD", category: "Mid Cap", sector: "Consumer" },
  { rank: 227, name: "KAYNES TECHNOLOGY INDIA LIMITED", nse: "KAYNES", category: "Mid Cap", sector: "IT" },
  { rank: 228, name: "Escorts Kubota Limited", nse: "ESCORTS", category: "Mid Cap", sector: "" },
  { rank: 229, name: "Radico Khaitan Ltd.", nse: "RADICO", category: "Mid Cap", sector: "FMCG" },
  { rank: 230, name: "Gujarat Fluorochemicals Limited", nse: "FLUOROCHEM", category: "Mid Cap", sector: "Chemicals" },
  { rank: 231, name: "Endurance Technologies Limited", nse: "ENDURANCE", category: "Mid Cap", sector: "IT" },
  { rank: 232, name: "KEI Industries Ltd.", nse: "KEI", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 233, name: "ASTRAL LIMITED", nse: "ASTRAL", category: "Mid Cap", sector: "Capital Goods" },
  { rank: 234, name: "Thermax Ltd.", nse: "THERMAX", category: "Mid Cap", sector: "" },
  { rank: 235, name: "Physicswallah Limited", nse: "PWL", category: "Mid Cap", sector: "" },
  { rank: 236, name: "UCO Bank", nse: "UCOBANK", category: "Mid Cap", sector: "Banking" },
  { rank: 237, name: "Blue Star Ltd", nse: "BLUESTARCO", category: "Mid Cap", sector: "Consumer" },
  { rank: 238, name: "Narayana Hrudayalaya Limited", nse: "NH", category: "Mid Cap", sector: "" },
  { rank: 239, name: "Tata Investment Corporation Ltd.", nse: "TATAINVEST", category: "Mid Cap", sector: "" },
  { rank: 240, name: "Godrej Industries Ltd.", nse: "GODREJIND", category: "Mid Cap", sector: "" },
  { rank: 241, name: "POONAWALLA FINCORP LIMITED", nse: "POONAWALLA", category: "Mid Cap", sector: "" },
  { rank: 242, name: "CRISIL Ltd.", nse: "CRISIL", category: "Mid Cap", sector: "" },
  { rank: 243, name: "K.P.R. Mill Ltd.", nse: "KPRMILL", category: "Mid Cap", sector: "" },
  { rank: 244, name: "CHOLAMANDALAM FINANCIAL HOLDINGS LIMITED", nse: "CHOLAHLDNG", category: "Mid Cap", sector: "Financial Services" },
  { rank: 2453, name: "M India Ltd.", nse: "3MINDIA", category: "Mid Cap", sector: "" },
  { rank: 246, name: "Ipca Laboratories Ltd.", nse: "IPCALAB", category: "Mid Cap", sector: "" },
  { rank: 247, name: "Piramal Finance Limited", nse: "PIRAMALFIN", category: "Mid Cap", sector: "Financial Services" },
  { rank: 248, name: "Apar Industries Ltd", nse: "APARINDS", category: "Mid Cap", sector: "" },
  { rank: 249, name: "SJVN LIMITED", nse: "SJVN", category: "Mid Cap", sector: "Power" },
  { rank: 250, name: "Global Health Limited", nse: "MEDANTA", category: "Mid Cap", sector: "Pharma" },
  { rank: 251, name: "ACC Ltd", nse: "ACC", category: "Small Cap", sector: "Cement" },
  { rank: 252, name: "Tata Elxsi Ltd", nse: "TATAELXSI", category: "Small Cap", sector: "IT" },
  { rank: 253, name: "NLC India Limited", nse: "NLCINDIA", category: "Small Cap", sector: "" },
  { rank: 254, name: "AWL AGRI BUSINESS LIMITED", nse: "AWL", category: "Small Cap", sector: "" },
  { rank: 255, name: "Central Bank of India", nse: "CENTRALBK", category: "Small Cap", sector: "Banking" },
  { rank: 256, name: "KPIT Technologies Ltd", nse: "KPITTECH", category: "Small Cap", sector: "IT" },
  { rank: 257, name: "Central Depository Services (India) Ltd.", nse: "--", category: "Small Cap", sector: "" },
  { rank: 258, name: "Delhivery Limited", nse: "DELHIVERY", category: "Small Cap", sector: "" },
  { rank: 259, name: "Aster DM Healthcare Limited", nse: "ASTERDM", category: "Small Cap", sector: "Pharma" },
  { rank: 260, name: "Exide Industries Ltd.", nse: "EXIDEIND", category: "Small Cap", sector: "Auto" },
  { rank: 261, name: "Go Digit General Insurance Limited", nse: "GODIGIT", category: "Small Cap", sector: "Insurance" },
  { rank: 262, name: "Honeywell Automation India Ltd.", nse: "HONAUT", category: "Small Cap", sector: "Auto" },
  { rank: 263, name: "Ajanta Pharma Ltd.", nse: "AJANTPHARM", category: "Small Cap", sector: "Pharma" },
  { rank: 264, name: "Metro Brands Limited", nse: "METROBRAND", category: "Small Cap", sector: "" },
  { rank: 265, name: "AIA Engineering Ltd.", nse: "AIAENG", category: "Small Cap", sector: "" },
  { rank: 266, name: "Cohance Lifesciences Limited", nse: "COHANCE", category: "Small Cap", sector: "Pharma" },
  { rank: 267, name: "Lic Housing Finance Ltd.", nse: "LICHSGFIN", category: "Small Cap", sector: "Financial Services" },
  { rank: 268, name: "Gillette India Ltd.", nse: "GILLETTE", category: "Small Cap", sector: "" },
  { rank: 269, name: "Gland Pharma Limited", nse: "GLAND", category: "Small Cap", sector: "Pharma" },
  { rank: 270, name: "Apollo Tyres Ltd", nse: "APOLLOTYRE", category: "Small Cap", sector: "" },
  { rank: 271, name: "The New India Assurance Company Limited", nse: "NIACL", category: "Small Cap", sector: "" },
  { rank: 272, name: "NBCC (India) Limited", nse: "NBCC", category: "Small Cap", sector: "" },
  { rank: 273, name: "ITI Limited (Indian Teleph.Ind.Ltd)", nse: "ITI", category: "Small Cap", sector: "" },
  { rank: 274, name: "Hindustan Copper Ltd.", nse: "HINDCOPPER", category: "Small Cap", sector: "Metals" },
  { rank: 275, name: "Garden Reach Shipbuilders & Engineers Limited", nse: "GRSE", category: "Small Cap", sector: "" },
  { rank: 276, name: "Motherson Sumi Wiring India Limited", nse: "MSUMI", category: "Small Cap", sector: "" },
  { rank: 277, name: "Gujarat Gas Limited", nse: "GUJGASLTD", category: "Small Cap", sector: "Oil & Gas" },
  { rank: 278, name: "ICICI Securities Limited", nse: "----", category: "Small Cap", sector: "" },
  { rank: 279, name: "Indraprashtha Gas Ltd.", nse: "IGL", category: "Small Cap", sector: "Oil & Gas" },
  { rank: 280, name: "Sona BLW Precision Forgings Limited", nse: "SONACOMS", category: "Small Cap", sector: "Auto" },
  { rank: 281, name: "AEGIS VOPAK TERMINALS LIMITED", nse: "AEGISVOPAK", category: "Small Cap", sector: "" },
  { rank: 282, name: "Krishna Institute of Medical Sciences Limited", nse: "KIMS", category: "Small Cap", sector: "Pharma" },
  { rank: 283, name: "Tata Technologies Limited", nse: "TATATECH", category: "Small Cap", sector: "IT" },
  { rank: 284, name: "Pine Labs Limited", nse: "PINELABS", category: "Small Cap", sector: "Pharma" },
  { rank: 286, name: "ELITECON INTERNATIONAL LIMITED", nse: "----", category: "Small Cap", sector: "" },
  { rank: 287, name: "Star Health and Allied Insurance Company Limited", nse: "STARHEALTH", category: "Small Cap", sector: "Pharma" },
  { rank: 288, name: "J.B. Chemicals & Pharmaceuticals Lt", nse: "JBCHEPHARM", category: "Small Cap", sector: "Pharma" },
  { rank: 289, name: "TVS Holdings Limited", nse: "TVSHLTD", category: "Small Cap", sector: "Auto" },
  { rank: 290, name: "IRB Infrastructure Developers Limited", nse: "IRB", category: "Small Cap", sector: "Infra" },
  { rank: 291, name: "Navin Fluorine International Limited", nse: "NAVINFLUOR", category: "Small Cap", sector: "" },
  { rank: 292, name: "SUMITOMO CHEMICAL INDIA LIMITED", nse: "SUMICHEM", category: "Small Cap", sector: "Chemicals" },
  { rank: 293, name: "AFFLE 3I LIMITED", nse: "AFFLE", category: "Small Cap", sector: "" },
  { rank: 294, name: "Aegis Logistics Ltd.", nse: "AEGISLOG", category: "Small Cap", sector: "" },
  { rank: 295, name: "Syngene International Limited", nse: "SYNGENE", category: "Small Cap", sector: "" },
  { rank: 296, name: "Bandhan Bank Limited", nse: "BANDHANBNK", category: "Small Cap", sector: "Banking" },
  { rank: 297, name: "Emcure Pharmaceuticals Limited", nse: "EMCURE", category: "Small Cap", sector: "Pharma" },
  { rank: 298, name: "Piramal Enterprises Limited", nse: "----", category: "Small Cap", sector: "" },
  { rank: 299, name: "Dr. Lal Pathlabs Limited", nse: "LALPATHLAB", category: "Small Cap", sector: "Pharma" },
  { rank: 300, name: "Amber Enterprises India Limited", nse: "AMBER", category: "Small Cap", sector: "" },
  { rank: 301, name: "PIRAMAL PHARMA LIMITED", nse: "PPLPHARMA", category: "Small Cap", sector: "Pharma" },
  { rank: 302, name: "ZF Commercial Vehicle Control Systems India Limited", nse: "ZFCVINDIA", category: "Small Cap", sector: "" },
  { rank: 303, name: "Nuvama Wealth Management Limited", nse: "NUVAMA", category: "Small Cap", sector: "" },
  { rank: 304, name: "Mangalore Refinery & Petrochemicals", nse: "MRPL", category: "Small Cap", sector: "Chemicals" },
  { rank: 305, name: "The Ramco Cements Limited", nse: "RAMCOCEM", category: "Small Cap", sector: "Cement" },
  { rank: 306, name: "Shyam Metalics and Energy Limited", nse: "SHYAMMETL", category: "Small Cap", sector: "Power" },
  { rank: 307, name: "Emami Ltd", nse: "EMAMILTD", category: "Small Cap", sector: "FMCG" },
  { rank: 308, name: "Firstsource Solutions Ltd.", nse: "FSL", category: "Small Cap", sector: "" },
  { rank: 309, name: "Inox Wind Limited", nse: "INOXWIND", category: "Small Cap", sector: "" },
  { rank: 310, name: "Deepak Nitrite Limited", nse: "DEEPAKNTR", category: "Small Cap", sector: "Chemicals" },
  { rank: 311, name: "EIH Ltd", nse: "EIHOTEL", category: "Small Cap", sector: "" },
  { rank: 312, name: "Wockhardt Ltd", nse: "WOCKPHARMA", category: "Small Cap", sector: "" },
  { rank: 313, name: "PTC Industries Ltd.", nse: "PTCIL", category: "Small Cap", sector: "" },
  { rank: 314, name: "Pfizer Ltd.", nse: "PFIZER", category: "Small Cap", sector: "" },
  { rank: 315, name: "Anand Rathi Wealth Limited", nse: "ANANDRATHI", category: "Small Cap", sector: "" },
  { rank: 316, name: "KIOCL Limited", nse: "KIOCL", category: "Small Cap", sector: "Oil & Gas" },
  { rank: 317, name: "Manappuram Finance Limited", nse: "MANAPPURAM", category: "Small Cap", sector: "Financial Services" },
  { rank: 318, name: "PNB Housing Finance Limited", nse: "PNBHOUSING", category: "Small Cap", sector: "Financial Services" },
  { rank: 319, name: "Brigade Enterprises Limited", nse: "BRIGADE", category: "Small Cap", sector: "Realty" },
  { rank: 320, name: "Bayer CropScience Limited.", nse: "----", category: "Small Cap", sector: "" },
  { rank: 321, name: "Aditya Birla Sun Life AMC Limited", nse: "ABSLAMC", category: "Small Cap", sector: "Financial Services" },
  { rank: 322, name: "National Securities Depository Limited", nse: "----", category: "Small Cap", sector: "" },
  { rank: 323, name: "Timken India Ltd", nse: "TIMKEN", category: "Small Cap", sector: "" },
  { rank: 324, name: "Himadri Speciality Chemical Ltd.", nse: "HSCL", category: "Small Cap", sector: "Chemicals" },
  { rank: 325, name: "Force Motors Limited", nse: "FORCEMOT", category: "Small Cap", sector: "Auto" },
  { rank: 326, name: "Welspun Corp Limited", nse: "WELCORP", category: "Small Cap", sector: "" },
  { rank: 327, name: "ANGEL ONE LIMITED", nse: "ANGELONE", category: "Small Cap", sector: "" },
  { rank: 328, name: "Tata Chemicals Ltd", nse: "TATACHEM", category: "Small Cap", sector: "Chemicals" },
  { rank: 329, name: "Asahi India Glass Ltd.", nse: "ASAHIINDIA", category: "Small Cap", sector: "" },
  { rank: 330, name: "AstraZeneca Pharma India Ltd.", nse: "ASTRAZEN", category: "Small Cap", sector: "Pharma" },
  { rank: 331, name: "Eris Lifesciences Limited", nse: "ERIS", category: "Small Cap", sector: "Pharma" },
  { rank: 332, name: "CESC Limited", nse: "CESC", category: "Small Cap", sector: "" },
  { rank: 333, name: "HBL ENGINEERING LIMITED", nse: "HBLENGINE", category: "Small Cap", sector: "" },
  { rank: 334, name: "SUN TV NETWORK LIMITED", nse: "SUNTV", category: "Small Cap", sector: "" },
  { rank: 335, name: "Karur Vysya Bank Ltd.", nse: "KARURVYSYA", category: "Small Cap", sector: "Banking" },
  { rank: 336, name: "Sagility Limited", nse: "SAGILITY", category: "Small Cap", sector: "" },
  { rank: 337, name: "Jyoti CNC Automation Limited", nse: "JYOTICNC", category: "Small Cap", sector: "Auto" },
  { rank: 338, name: "KEC International Ltd.", nse: "KEC", category: "Small Cap", sector: "Infra" },
  { rank: 339, name: "Aadhar Housing Finance Limited", nse: "AADHARHFC", category: "Small Cap", sector: "Financial Services" },
  { rank: 340, name: "IIFL FINANCE LIMITED", nse: "IIFL", category: "Small Cap", sector: "Financial Services" },
  { rank: 341, name: "Redington Limited", nse: "REDINGTON", category: "Small Cap", sector: "" },
  { rank: 342, name: "Hatsun Agro Products Ltd.", nse: "HATSUN", category: "Small Cap", sector: "" },
  { rank: 343, name: "CreditAccess Grameen Ltd.", nse: "CREDITACC", category: "Small Cap", sector: "Cement" },
  { rank: 344, name: "Urban Company Limited", nse: "URBANCO", category: "Small Cap", sector: "" },
  { rank: 345, name: "JSW Holdings Limited", nse: "JSWHL", category: "Small Cap", sector: "" },
  { rank: 346, name: "PUNJAB & SIND BANK", nse: "PSB", category: "Small Cap", sector: "Banking" },
  { rank: 347, name: "Onesource Specialty Pharma Limited", nse: "ONESOURCE", category: "Small Cap", sector: "Pharma" },
  { rank: 348, name: "KALPATARU PROJECTS INTERNATIONAL LIMITED", nse: "KPIL", category: "Small Cap", sector: "" },
  { rank: 349, name: "Ather Energy Limited", nse: "ATHERENERG", category: "Small Cap", sector: "Power" },
  { rank: 350, name: "Sundram Fasteners Ltd.", nse: "SUNDRMFAST", category: "Small Cap", sector: "" },
  { rank: 351, name: "ADITYA BIRLA REAL ESTATE LIMITED", nse: "ABREL", category: "Small Cap", sector: "Realty" },
  { rank: 352, name: "Ola Electric Mobility Limited", nse: "OLAELEC", category: "Small Cap", sector: "" },
  { rank: 353, name: "Chalet Hotels Limited", nse: "CHALET", category: "Small Cap", sector: "Capital Goods" },
  { rank: 354, name: "Anant Raj Limited", nse: "ANANTRAJ", category: "Small Cap", sector: "" },
  { rank: 355, name: "Chambal Fertilisers & Chemicals Ltd", nse: "CHAMBLFERT", category: "Small Cap", sector: "Chemicals" },
  { rank: 356, name: "eClerx Services Limited", nse: "ECLERX", category: "Small Cap", sector: "" },
  { rank: 357, name: "Castrol India Ltd", nse: "CASTROLIND", category: "Small Cap", sector: "" },
  { rank: 358, name: "SCHNEIDER ELECTRIC INFRASTRUCTURE LIMITED", nse: "SCHNEIDER", category: "Small Cap", sector: "Infra" },
  { rank: 359, name: "Poly Medicure Ltd", nse: "POLYMED", category: "Small Cap", sector: "Pharma" },
  { rank: 360, name: "DCM Shriram Limited", nse: "DCMSHRIRAM", category: "Small Cap", sector: "" },
  { rank: 361, name: "Devyani International Limited", nse: "DEVYANI", category: "Small Cap", sector: "" },
  { rank: 362, name: "BASF India Ltd", nse: "BASF", category: "Small Cap", sector: "" },
  { rank: 363, name: "Tenneco Clean Air India Limited", nse: "TENNIND", category: "Small Cap", sector: "Chemicals" },
  { rank: 364, name: "Kansai Nerolac Paints", nse: "KANSAINER", category: "Small Cap", sector: "" },
  { rank: 365, name: "Neuland Laboratories Limited.", nse: "NEULANDLAB", category: "Small Cap", sector: "" },
  { rank: 366, name: "Crompton Greaves Consumer Electricals Limited", nse: "CROMPTON", category: "Small Cap", sector: "" },
  { rank: 367, name: "Computer Age Management Services Limited", nse: "CAMS", category: "Small Cap", sector: "" },
  { rank: 368, name: "E.I.D. Parry (India) Ltd.", nse: "EIDPARRY", category: "Small Cap", sector: "" },
  { rank: 369, name: "KFin Technologies Limited", nse: "KFINTECH", category: "Small Cap", sector: "IT" },
  { rank: 370, name: "Reliance Power Limited", nse: "RPOWER", category: "Small Cap", sector: "Power" },
  { rank: 371, name: "Bikaji Foods International Limited", nse: "BIKAJI", category: "Small Cap", sector: "" },
  { rank: 372, name: "Kajaria Ceramics Ltd", nse: "KAJARIACER", category: "Small Cap", sector: "" },
  { rank: 373, name: "Atul Limited.", nse: "ATUL", category: "Small Cap", sector: "Chemicals" },
  { rank: 374, name: "Sarda Energy & Minerals Ltd", nse: "SARDAEN", category: "Small Cap", sector: "Power" },
  { rank: 375, name: "ALEMBIC PHARMACEUTICALS LIMITED", nse: "APLLTD", category: "Small Cap", sector: "Pharma" },
  { rank: 376, name: "Deepak Fertilizers &Petrochemicals", nse: "DEEPAKFERT", category: "Small Cap", sector: "Chemicals" },
  { rank: 377, name: "Brainbees Solutions Limited", nse: "FIRSTCRY", category: "Small Cap", sector: "" },
  { rank: 378, name: "JSW CEMENT LIMITED", nse: "JSWCEMENT", category: "Small Cap", sector: "Cement" },
  { rank: 379, name: "Sai Life Sciences Limited", nse: "SAILIFE", category: "Small Cap", sector: "" },
  { rank: 380, name: "Capri Global Capital Limited", nse: "CGCL", category: "Small Cap", sector: "Financial Services" },
  { rank: 381, name: "Amara Raja Energy & Mobility Limited", nse: "ARE&M", category: "Small Cap", sector: "Power" },
  { rank: 382, name: "Grindwell Norton Ltd.", nse: "GRINDWELL", category: "Small Cap", sector: "" },
  { rank: 383, name: "Vinati Organics Ltd.", nse: "VINATIORGA", category: "Small Cap", sector: "Chemicals" },
  { rank: 384, name: "Maharashtra Scooters Ltd.", nse: "MAHSCOOTER", category: "Small Cap", sector: "" },
  { rank: 385, name: "JUBILANT PHARMOVA LIMITED", nse: "JUBLPHARMA", category: "Small Cap", sector: "" },
  { rank: 386, name: "Zensar Technologies Ltd.", nse: "ZENSARTECH", category: "Small Cap", sector: "IT" },
  { rank: 387, name: "Five-Star Business Finance Ltd.", nse: "FIVESTAR", category: "Small Cap", sector: "Financial Services" },
  { rank: 388, name: "Triveni Turbine Limited", nse: "TRITURBINE", category: "Small Cap", sector: "" },
  { rank: 389, name: "RBL Bank Limited", nse: "RBLBANK", category: "Small Cap", sector: "Banking" },
  { rank: 390, name: "Carborundum Universal Ltd.", nse: "CARBORUNIV", category: "Small Cap", sector: "" },
  { rank: 391, name: "Gujarat State Petronet Ltd.", nse: "GSPL", category: "Small Cap", sector: "Oil & Gas" },
  { rank: 392, name: "Ratnamani Metals & Tubes Ltd", nse: "RATNAMANI", category: "Small Cap", sector: "Metals" },
  { rank: 393, name: "PG Electroplast Limited", nse: "PGEL", category: "Small Cap", sector: "" },
  { rank: 394, name: "NAVA LIMITED", nse: "NAVA", category: "Small Cap", sector: "" },
  { rank: 395, name: "Ventive Hospitality Limited", nse: "VENTIVE", category: "Small Cap", sector: "Pharma" },
  { rank: 396, name: "City Union Bank Ltd", nse: "CUB", category: "Small Cap", sector: "Banking" },
  { rank: 397, name: "Century Plyboards (India) Ltd.", nse: "CENTURYPLY", category: "Small Cap", sector: "" },
  { rank: 398, name: "BEML Ltd", nse: "BEML", category: "Small Cap", sector: "" },
  { rank: 399, name: "Vedant Fashions Limited", nse: "MANYAVAR", category: "Small Cap", sector: "" },
  { rank: 400, name: "Aditya Birla Lifestyle Brands Limited", nse: "ABLBL", category: "Small Cap", sector: "" },
  { rank: 401, name: "NETWEB TECHNOLOGIES INDIA LIMITED", nse: "NETWEB", category: "Small Cap", sector: "IT" },
  { rank: 402, name: "TBO TEK LIMITED", nse: "TBOTEK", category: "Small Cap", sector: "" },
  { rank: 403, name: "Concord Biotech Limited", nse: "CONCORDBIO", category: "Small Cap", sector: "IT" },
  { rank: 404, name: "Aditya Infotech Limited", nse: "CPPLUS", category: "Small Cap", sector: "IT" },
  { rank: 405, name: "TRAVEL FOOD SERVICES LIMITED", nse: "TRAVELFOOD", category: "Small Cap", sector: "" },
  { rank: 406, name: "UTI Asset Management Company Limited", nse: "UTIAMC", category: "Small Cap", sector: "Financial Services" },
  { rank: 407, name: "Sobha Limited", nse: "SOBHA", category: "Small Cap", sector: "Realty" },
  { rank: 408, name: "LMW Limited", nse: "LMW", category: "Small Cap", sector: "" },
  { rank: 409, name: "ACME Solar Holdings Limited", nse: "ACMESOLAR", category: "Small Cap", sector: "" },
  { rank: 410, name: "IRCON International Ltd", nse: "IRCON", category: "Small Cap", sector: "" },
  { rank: 411, name: "Gabriel India Ltd.", nse: "GABRIEL", category: "Small Cap", sector: "" },
  { rank: 412, name: "Gujarat Mineral Development Corpora", nse: "GMDCLTD", category: "Small Cap", sector: "" },
  { rank: 413, name: "Craftsman Automation Limited", nse: "CRAFTSMAN", category: "Small Cap", sector: "Auto" },
  { rank: 414, name: "Choice International Ltd", nse: "CHOICEIN", category: "Small Cap", sector: "" },
  { rank: 415, name: "Elgi Equipments Ltd.", nse: "ELGIEQUIP", category: "Small Cap", sector: "" },
  { rank: 416, name: "Natco Pharma Ltd.", nse: "NATCOPHARM", category: "Small Cap", sector: "Pharma" },
  { rank: 417, name: "V-Guard Industries Ltd.", nse: "VGUARD", category: "Small Cap", sector: "" },
  { rank: 418, name: "Aptus Value Housing Finance India Limited", nse: "APTUS", category: "Small Cap", sector: "Financial Services" },
  { rank: 419, name: "CIE Automotive India Limited", nse: "CIEINDIA", category: "Small Cap", sector: "Auto" },
  { rank: 420, name: "SIGNATUREGLOBAL (INDIA) LIMITED", nse: "SIGNATURE", category: "Small Cap", sector: "" },
  { rank: 421, name: "Techno Electric & Engineering Company Limited", nse: "TECHNOE", category: "Small Cap", sector: "IT" },
  { rank: 422, name: "Whirlpool of India Ltd", nse: "WHIRLPOOL", category: "Small Cap", sector: "" },
  { rank: 423, name: "JM Financial Limited", nse: "JMFINANCIL", category: "Small Cap", sector: "Financial Services" },
  { rank: 424, name: "GODAWARI POWER AND ISPAT LTD.", nse: "GPIL", category: "Small Cap", sector: "Power" },
  { rank: 425, name: "Afcons Infrastructure Limited", nse: "AFCONS", category: "Small Cap", sector: "Infra" },
  { rank: 426, name: "Akzo Nobel India Limited", nse: "AKZOINDIA", category: "Small Cap", sector: "" },
  { rank: 427, name: "Allied Blenders and Distillers Limited", nse: "ABDL", category: "Small Cap", sector: "" },
  { rank: 428, name: "Caplin Point Laboratories Ltd.", nse: "CAPLIPOINT", category: "Small Cap", sector: "" },
  { rank: 430, name: "International Gemmological Institute India Limited", nse: "IGIL", category: "Small Cap", sector: "" },
  { rank: 431, name: "DOMS Industries Limited", nse: "DOMS", category: "Small Cap", sector: "" },
  { rank: 432, name: "LT Foods Limited", nse: "LTFOODS", category: "Small Cap", sector: "" },
  { rank: 433, name: "Kirloskar Brothers Ltd.", nse: "KIRLOSBROS", category: "Small Cap", sector: "" },
  { rank: 434, name: "Dr. Agarwal\'s Health Care Limited", nse: "AGARWALEYE", category: "Small Cap", sector: "Pharma" },
  { rank: 435, name: "JBM Auto Limited", nse: "JBMA", category: "Small Cap", sector: "Auto" },
  { rank: 436, name: "R R KABEL LIMITED", nse: "RRKABEL", category: "Small Cap", sector: "" },
  { rank: 437, name: "Great Eastern Shipping Co. Ltd.", nse: "GESHIP", category: "Small Cap", sector: "" },
  { rank: 438, name: "GALLANTT ISPAT LIMITED", nse: "GALLANTT", category: "Small Cap", sector: "" },
  { rank: 439, name: "IFCI Ltd.", nse: "IFCI", category: "Small Cap", sector: "" },
  { rank: 440, name: "NIVA BUPA HEALTH INSURANCE COMPANY LIMITED", nse: "NIVABUPA", category: "Small Cap", sector: "Pharma" },
  { rank: 441, name: "IndiaMART InterMESH Limited", nse: "INDIAMART", category: "Small Cap", sector: "" },
  { rank: 442, name: "Paradeep Phosphates Limited", nse: "PARADEEP", category: "Small Cap", sector: "" },
  { rank: 443, name: "Ceat Ltd.", nse: "CEATLTD", category: "Small Cap", sector: "" },
  { rank: 444, name: "Trident Ltd", nse: "TRIDENT", category: "Small Cap", sector: "" },
  { rank: 445, name: "Rainbow Children\'s Medicare Limited", nse: "RAINBOW", category: "Small Cap", sector: "Pharma" },
  { rank: 446, name: "INTELLECT DESIGN ARENA LIMITED", nse: "INTELLECT", category: "Small Cap", sector: "IT" },
  { rank: 447, name: "Syrma SGS Technology Limited", nse: "SYRMA", category: "Small Cap", sector: "IT" },
  { rank: 448, name: "Fine Organic Industries Limited", nse: "FINEORG", category: "Small Cap", sector: "Chemicals" },
  { rank: 449, name: "Bata India Limited", nse: "BATAINDIA", category: "Small Cap", sector: "" },
  { rank: 450, name: "Nuvoco Vistas Corporation Limited", nse: "NUVOCO", category: "Small Cap", sector: "" },
  { rank: 451, name: "Swan Corp Limited", nse: "SWANCORP", category: "Small Cap", sector: "" },
  { rank: 452, name: "Kirloskar Oil Engines Limited", nse: "KIRLOSENG", category: "Small Cap", sector: "Oil & Gas" },
  { rank: 453, name: "BLS International Services Ltd", nse: "BLS", category: "Small Cap", sector: "" },
  { rank: 454, name: "Aarti Industries Ltd", nse: "AARTIIND", category: "Small Cap", sector: "" },
  { rank: 455, name: "Leela Palaces Hotels & Resorts Limited", nse: "THELEELA", category: "Small Cap", sector: "" },
  { rank: 456, name: "Emmvee Photovoltaic Power Limited", nse: "EMMVEE", category: "Small Cap", sector: "Power" },
  { rank: 457, name: "Supreme Petrochem Ltd.", nse: "SPLPETRO", category: "Small Cap", sector: "" },
  { rank: 458, name: "Blue Dart Express Ltd.", nse: "BLUEDART", category: "Small Cap", sector: "" },
  { rank: 459, name: "Zydus Wellness Limited", nse: "ZYDUSWELL", category: "Small Cap", sector: "" },
  { rank: 460, name: "KSB LIMITED", nse: "KSB", category: "Small Cap", sector: "" },
  { rank: 461, name: "PCBL Chemical Limited", nse: "PCBL", category: "Small Cap", sector: "Chemicals" },
  { rank: 462, name: "JUPITER WAGONS LIMITED", nse: "JWL", category: "Small Cap", sector: "" },
  { rank: 463, name: "Cemindia Projects Limited", nse: "CEMPRO", category: "Small Cap", sector: "" },
  { rank: 464, name: "Zen Technologies Ltd.", nse: "ZENTEC", category: "Small Cap", sector: "IT" },
  { rank: 465, name: "Jain Resource Recycling Limited", nse: "JAINREC", category: "Small Cap", sector: "" },
  { rank: 466, name: "Indian Energy Exchange Limited", nse: "IEX", category: "Small Cap", sector: "Power" },
  { rank: 467, name: "Godrej Agrovet Limited", nse: "GODREJAGRO", category: "Small Cap", sector: "" },
  { rank: 468, name: "The Bombay Burmah Trading Corporation Ltd.", nse: "BBTC", category: "Small Cap", sector: "" },
  { rank: 469, name: "Cyient Limited", nse: "CYIENT", category: "Small Cap", sector: "IT" },
  { rank: 470, name: "Indegene Limited", nse: "INDGN", category: "Small Cap", sector: "" },
  { rank: 471, name: "AAVAS Financiers Limited", nse: "AAVAS", category: "Small Cap", sector: "Financial Services" },
  { rank: 472, name: "Minda Corporation Limited", nse: "MINDACORP", category: "Small Cap", sector: "" },
  { rank: 473, name: "BELRISE INDUSTRIES LIMITED", nse: "BELRISE", category: "Small Cap", sector: "" },
  { rank: 474, name: "Cello World Limited", nse: "CELLO", category: "Small Cap", sector: "" },
  { rank: 475, name: "Jaiprakash Power Ventures Limited", nse: "JPPOWER", category: "Small Cap", sector: "Power" },
  { rank: 476, name: "Transformers and Rectifiers (India) Limited", nse: "TARIL", category: "Small Cap", sector: "" },
  { rank: 477, name: "Newgen Software Technologies Limited", nse: "NEWGEN", category: "Small Cap", sector: "IT" },
  { rank: 478, name: "Anupam Rasayan India Limited", nse: "ANURAS", category: "Small Cap", sector: "" },
  { rank: 479, name: "Granules India Ltd.", nse: "GRANULES", category: "Small Cap", sector: "" },
  { rank: 480, name: "Home First Finance Company India Limited", nse: "HOMEFIRST", category: "Small Cap", sector: "Financial Services" },
  { rank: 481, name: "GRAVITA INDIA LIMITED", nse: "GRAVITA", category: "Small Cap", sector: "" },
  { rank: 482, name: "Mahanagar Gas Limited", nse: "MGL", category: "Small Cap", sector: "Oil & Gas" },
  { rank: 483, name: "Usha Martin Ltd.", nse: "USHAMART", category: "Small Cap", sector: "" },
  { rank: 484, name: "Tega Industries Limited", nse: "TEGA", category: "Small Cap", sector: "" },
  { rank: 485, name: "Lemon Tree Hotels Limited", nse: "LEMONTREE", category: "Small Cap", sector: "" },
  { rank: 486, name: "Vardhman Textiles Limted", nse: "VTL", category: "Small Cap", sector: "" },
  { rank: 487, name: "NCC Limited", nse: "NCC", category: "Small Cap", sector: "" },
  { rank: 488, name: "Finolex Cables Ltd.", nse: "FINCABLES", category: "Small Cap", sector: "" },
  { rank: 489, name: "Action Construction Equipments Ltd.", nse: "ACE", category: "Small Cap", sector: "Infra" },
  { rank: 490, name: "SKF INDIA (INDUSTRIAL) LIMITED", nse: "SKFINDUS", category: "Small Cap", sector: "" },
  { rank: 491, name: "EMBASSY DEVELOPMENTS LIMITED", nse: "EMBDL", category: "Small Cap", sector: "" },
  { rank: 492, name: "Elecon Engineering Co.Ltd.", nse: "ELECON", category: "Small Cap", sector: "" },
  { rank: 493, name: "Jindal Saw Ltd.", nse: "JINDALSAW", category: "Small Cap", sector: "" },
  { rank: 494, name: "Inox Wind Energy Limited", nse: "----", category: "Small Cap", sector: "Power" },
  { rank: 495, name: "WELSPUN LIVING LIMITED", nse: "WELSPUNLIV", category: "Small Cap", sector: "" },
  { rank: 496, name: "NMDC Steel Limited", nse: "NSLNISP", category: "Small Cap", sector: "Metals" },
  { rank: 497, name: "ACUTAAS CHEMICALS LIMITED", nse: "ACUTAAS", category: "Small Cap", sector: "Chemicals" },
  { rank: 498, name: "RITES Limited", nse: "RITES", category: "Small Cap", sector: "" },
  { rank: 499, name: "CCL Products (India) Ltd.", nse: "CCL", category: "Small Cap", sector: "" },
  { rank: 500, name: "Finolex Industries Ltd.", nse: "FINPIPE", category: "Small Cap", sector: "" },
  { rank: 501, name: "Sammaan Capital Limited", nse: "SAMMAANCAP", category: "Small Cap", sector: "Financial Services" },
  { rank: 502, name: "Ingersoll-Rand (India) Ltd.", nse: "INGERRAND", category: "Small Cap", sector: "" },
  { rank: 503, name: "India Cements Ltd.", nse: "INDIACEM", category: "Small Cap", sector: "Cement" },
  { rank: 504, name: "Blue Jet Healthcare Limited", nse: "BLUEJET", category: "Small Cap", sector: "Pharma" },
];
