#!/bin/bash
echo "AZURE_STORAGE_CONNECTION_STRING length: ${#AZURE_STORAGE_CONNECTION_STRING}"
echo "POSTGRES_CONNECTION_STRING length: ${#POSTGRES_CONNECTION_STRING}"
echo "SUPABASE_DB_CONNECTION_STRING length: ${#SUPABASE_DB_CONNECTION_STRING}"
echo "NEXT_PUBLIC_SUPABASE_URL length: ${#NEXT_PUBLIC_SUPABASE_URL}"
echo "SUPABASE_SERVICE_ROLE_KEY length: ${#SUPABASE_SERVICE_ROLE_KEY}"
echo "AZURE_STORAGE_CONTAINER value: $AZURE_STORAGE_CONTAINER"
